elfin:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000

    time_delay_controller:
      type: elfin_controller/TimeDelayController
      joints: 
          - elfin_joint1
          - elfin_joint2
          - elfin_joint3
          - elfin_joint4
          - elfin_joint5
          - elfin_joint6
    
    gravity_comp_controller:
      type: elfin_controller/GravityCompController
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
      joint1:
        pid: {p: 100.0, i: 0, d: 10.0}
      joint2: 
        pid: {p: 100.0, i: 0, d: 10.0}
      joint3: 
        pid: {p: 100.0, i: 0, d: 10.0}
      joint4: 
        pid: {p: 100.0, i: 0, d: 10.0}
      joint5: 
        pid: {p: 100.0, i: 0, d: 10.0}
      joint6: 
        pid: {p: 100.0, i: 0, d: 10.0}

      # elfin_joint1:
      #   pid: {p: 100.0, i: 0, d: 10.0}
      # elfin_joint2:
      #   pid: {p: 100.0, i: 0, d: 10.0}
      # elfin_joint3:
      #   pid: {p: 100.0, i: 0, d: 10.0}
      # elfin_joint4:
      #   pid: {p: 100.0, i: 0, d: 10.0}
      # elfin_joint5:
      #   pid: {p: 100.0, i: 0, d: 10.0}
      # elfin_joint6:
      #   pid: {p: 100.0, i: 0, d: 10.0}
