elfin:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000
    
    gravity_comp_controller:
      type: arm_controllers/GravityCompController
      joints:
        - elfin_joint1
        - elfin_joint2
        - elfin_joint3
        - elfin_joint4
        - elfin_joint5
        - elfin_joint6
      gains:
        elfin_joint1: 
          pid: {p: 10.0, i: 0, d: 1.0}
        elfin_joint2: 
          pid: {p: 10.0, i: 0, d: 1.0}
        elfin_joint3: 
          pid: {p: 10.0, i: 0, d: 1.0}
        elfin_joint4: 
          pid: {p: 10.0, i: 0, d: 1.0}
        elfin_joint5: 
          pid: {p: 10.0, i: 0, d: 1.0}
        elfin_joint6: 
          pid: {p: 10.0, i: 1.0, d: 1.0}
      root_link: world
      tip_link: elfin_link6